bird_number: 50
x_interval: [-450.0, 50.0]
y_interval: [300.0, 600.0]
x_velocity_interval: [0.0, 10.0]
y_velocity_interval: [-20.0, 20.0]
attraction_coefficient: 0.01
reflection_limit: 100
speeding_limit: 10000
speeding_coefficient: 0.125
x_axis: [-500, 1500]
y_axis: [-500, 1500]
frames: 200
interval: 50
